CompanyCaseGoogle/ResumeParser/urls.py
from . import views
from django.urls import path

app_name = 'ResumeParser'
urlpatterns = [
    path('', views.index, name='index'),
    path('submit/<int:opening_id>', views.resumeSubmission, name="submit"),
    path('review/<int:opening_id>', views.adminReview, name="review"),

]

CompanyCaseGoogle/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ResumeParser.urls')),
    path('accounts/', include('allauth.urls')),
    path("__reload__/", include("django_browser_reload.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CompanyCaseGoogle/ResumeParser/models.py
from email.policy import default
import math
from pickletools import pydict
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from ResumeParser.jsonfield import JSONField
import json
    #always ignore capitloization
    # weight doesnt have to add up to 1 -> we will convert it afterwards
    # TaregtNum_ut_Weight-> Up to a certain weight given big enough numb
    # TargetOcc_uc_Weight-> Up to a certain weight given enough occ
        # look for tool

default_weighting= {
    'Work Experience': [.25, {'Duration of Experience':[r'[0-9]+ years of experience', 9, 'UT', 1]}],
    'Tools': [.30, {
       'react experience' : [ r'react', 1, 'UC', 1],
        'django experience' :[r'django', 1, 'UC', 1],
        'tailwind experience' :[r'tailwind', 1, 'UC', 1],
        }]
    }

def normalize_weighting(py_dict):
    weighting = py_dict
    top_level_sum = 0
    for title, weight in weighting.items():
        low_level_sum = 0
        for redex, tar_weight in weight[1].items():
            low_level_sum += tar_weight[-1]

        for redex, tar_weight in weight[1].items():
            tar_weight[-1] = math.floor((tar_weight[-1] / low_level_sum) * 1000) / 1000
        top_level_sum += float(weight[0])

    for title, weight in weighting.items():
        weighting[title][0] = math.floor((float(weight[0]) / top_level_sum) * 1000) / 1000
normalize_weighting( default_weighting)


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    resumeadmin = models.BooleanField(default=False)
    def __str__(self) -> str:
        display_name = self.user.first_name + " " + self.user.last_name
        if display_name.strip() == "":
            return self.user.username
        return self.user.first_name + " " + self.user.last_name

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Opening(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length = 70, default="", blank = True)
    #weight of various substrings
    # weight -> what that weight is made from

    weighting = JSONField(default=json.dumps(default_weighting))

    def save(self, *args, **kwargs):
        super(Opening, self).save(*args, **kwargs)
        self.normalizeWeighting()

    def normalizeWeighting(self):
        normalize_weighting(self.weighting)
    
    def getWeighting(self):
        return(self.weighting)

    def __str__(self) -> str:
        return self.name


from django.core.validators import FileExtensionValidator
class Application(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    apply_for = models.ForeignKey(Opening, on_delete=models.CASCADE)
    resume = models.FileField(upload_to="UploadedResumes", validators=[
        FileExtensionValidator( ['pdf', 'docx'] ),
        ],
        help_text="Please Submit PDF or DOCX file format"
        )
    REQUIRED_FIELDS = [first_name, last_name, email, apply_for, resume]

    def name(self):
        return self.first_name + " " + self.last_name

CompanyCaseGoogle/ResumeParser/forms.py
from multiprocessing import AuthenticationError
from django.forms import ModelForm, ClearableFileInput
from ResumeParser.models import Application
from django.utils.translation import gettext_lazy as _

class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = ['first_name', 'last_name', 'email', 'apply_for', 'resume']
        labels = {
            'apply_for': _("Application Choice"),
            }
        
        widgets = {
            "resume": ClearableFileInput(attrs={"accept":"pdf,.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"})
        }

CompanyCaseGoogle/ResumeParser/views.py
from django.shortcuts import redirect, render
from ResumeParser.forms import ApplicationForm
from django.http import HttpResponse
from django.contrib import messages
from ResumeParser.models import Opening
from django.contrib.auth.decorators import login_required 

def admin_required(function):
    def wrapper(request, *args, **kw):
        user=request.user  
        if (not user.profile.resumeadmin):
            return HttpResponse("<h1> User is not an Admin </h1>")
        return function(request, *args, **kw)
    return wrapper

# Create your views here.
def index(request):
    openings = Opening.objects.all()
    context = {
        "opening" : openings,
    }
    return render(request, "ResumeParser/index.html", context)

def resumeSubmission(request, opening_id):
    if request.method == "POST":
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Form submission successful')
    context = {
        "form": ApplicationForm,
    }
    return render(request, "ResumeParser/submit.html", context)


@login_required
@admin_required
def adminReview(request, opening_id):
    the_opening = Opening.objects.get(pk=opening_id)
    context = {
        "opening":the_opening,
    }
    return render(request, "ResumeParser/review.html", context)

CompanyCaseGoogle/mysite/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "landing.html")

CompanyCaseGoogle/ResumeParser/templates/ResumeParser/base.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    {% block header %}
    {% endblock header %}
</head>
<body>

{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span></button></div>
{% endfor %}
{% endif %}

{% block content %}
{% endblock content %}

</body>
</html>

CompanyCaseGoogle/ResumeParser/templates/ResumeParser/index.html
{% extends "ResumeParser/base.html" %}
{% load static %}
{% block header %}
<title>Homepage | ResumeParser</title>
<link rel="stylesheet" href="{% static 'ResumeParser/css/index.css' %}">

{% endblock header %}

{% block content %}

{% if user.is_authenticated %}
    <p class="absolute font-extrabold right-0">Welcome, {{ user.profile }} !</p>
    {% else %}
    Not Logged In
    {% endif %}

<div class="flex items-center flex-col h-screen">
  <h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">ResumeParser Homepage</h1>
  <h2 class="font-normal leading-tight text-4xl mt-0 mb-2 text-blue-600">Please select from the Positions Below</h2>

  <!-- table options -->
  <div class="flex justify-between items-start w-8/12 p-3 ">
    <!-- sort -->
    <div class="rounded-lg">
      <span class="flex items-center justify-space-around">
        <img class="w-12" src="{% static 'ResumeParser/imgs/sort_by.png' %}" alt="">
        <p class="text-4x1 font-medium text-center object-center">Sort By:</p>
      </span>
    </div>
    <div onclick="modeToggle()">

      <div id="reviewer_switch"  class="bg-gray-400 w-64 h-16 rounded-md flex items-center justify-around">
        <div style="width: 103.79px; background-color: #4AE250;" class="h-16 rounded-md flex items-center justify-center">
          <span> Applicant </span>
        </div>
        <div style="width: 103.79px; background-color: #FB5858;" class="h-16 rounded-md flex items-center justify-center">
        <span> Reviewer </span>
        </div>
      </div>

      <div id="cover" style="left: 8rem/* 128px */;" class="bg-gray-200 z-10 inline-block bottom-16 relative rounded-md w-32 h-16 left-32"></div>

    </div>
  </div>
  
  <table id="positions_table" class="w-8/12 text-center text-2xl">
    
      <tr>
        <td></td>
        <td>id:</td>
        <td>title:</td>
      </tr>
    
    {% for open in opening %}
    <tr onclick="go_to('{{open.id}}')">
      <!-- &#9733; -->
        <td class="text-4xl font-bold ">&#9734;</td><td>{{open.id}}</td><td>{{open.name}}</td>
    </tr>
    <script>
      
      
    </script>
    {% endfor %}
  </table>
</div>

<script>
  const submit_base = "{% url 'ResumeParser:submit' 1 %}".slice(0, -1);
  const review_base = "{% url 'ResumeParser:review' 1 %}".slice(0, -1);
</script>
<script src="{% static 'ResumeParser/js/index.js' %}"></script>

{% endblock content %}

CompanyCaseGoogle/ResumeParser/templates/ResumeParser/review.html
{% extends "ResumeParser/base.html" %}
{% load static %}
{% block header %}
<title>Homepage | Review</title>
<link rel="stylesheet" href="{% static 'ResumeParser/css/review.css' %}">
<link rel="stylesheet" href="{% static 'ResumeParser/css/sortable.min.css' %}">
{% endblock header %}


{% block content %}

<h1 class="font-medium leading-tight text-2xl mt-0 mb-2 text-blue-600">Applications Name: {{opening.name}}</h1>
{% with weighting=opening.weighting %}
{% with applications=opening.application_set.all %}

<h1 class="font-medium leading-tight text-1xl mt-0 mb-2 text-blue-600">Nums_of_Applications: {{applications|length}}</h1>
<div class="flex justify-between items-stretch">
    <h1 class="font-medium leading-tight text-1xl mt-0 mb-2 text-blue-600">See Weighting Breakdown Below</h1>
    <button class="float-right rounded-md bg-slate-200 p-1"><h1 class="font-medium leading-tight text-1xl mt-0 mb-2 text-blue-600">Edit Breakdown</h1></button>

</div>
<script>
    var users = []
    {% for app in applications %}
    users.push({id: {{app.id}},  resume:"{{app.resume}}", name: "{{app.name}}"})
    {% endfor %}
    weighting ="{{weighting}}".replaceAll("&#x27;", '"');
    weighting = JSON.parse(weighting);
    console.log(weighting);


</script>

{% endwith %}
<div class="flex flex-col justify-center items-center">
    <div style="background-color: #D9D9D9;" class="w-11/12  flex justify-between">
        {% for big_catagory_title, details in weighting.items %}
        <div style="width: calc({{details.0}}% * 100);"class="flex flex-col h-1/2 border-spacing-1 border-black" >
            <div class="random_color w-[100%] flex items-center justify-center">
                <span style="background-color:#00FEFE">{{big_catagory_title}} : {{details.0}}</span>
            </div>
            <div class="flex items-center justify-between">
                {% for title, other_details in details.1.items %}
                <div style="border: solid black; width: calc({{other_details.3}}% * 100);">
                    {{title}} : {{other_details.3}}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endwith %}

<!-- Table of resumes based on weighting -->
<table  class="sortable w-screen text-center text-2xl mt-5" >
    <thead>
      <tr>
        <th></th>
        <th><span>Id</span></th>
        <th>Score</th>
        <th>Name</th>

      </tr>
    </thead>
    <tbody id="resume_details">

    </tbody>
  </table>
</div>




<script src="https://cdnjs.cloudflare.com/ajax/libs/docxtemplater/3.26.2/docxtemplater.js"></script>
<script src="https://unpkg.com/pizzip@3.1.1/dist/pizzip.js"></script>
<script src="https://unpkg.com/pizzip@3.1.1/dist/pizzip-utils.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="{% static 'ResumeParser/js/review.js' %}"></script>
<script src="{% static 'ResumeParser/js/sortable.min.js' %}"></script>

{% endblock content %}

CompanyCaseGoogle/ResumeParser/templates/ResumeParser/submit.html
{% extends "ResumeParser/base.html" %}

{% block header %}
<title>Homepage | Application Portal</title>

{% endblock header %}
{% block content %}
<form action="" method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
<input type = "submit" value = "Submit">
{% endblock content %}

CompanyCaseGoogle/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>